name: Test the project

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

jobs:
  test:
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
        node:
          - '14'
          - '16'
        include:
          # Enable coverage on the fastest job only
          - os: 'ubuntu-latest'
            node: '16'
            ENABLE_CODE_COVERAGE: true
    env:
      ENABLE_CODE_COVERAGE: ${{ matrix.ENABLE_CODE_COVERAGE }}

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Typecheck the code
        run: npm run type-check

      - name: Lint the code
        run: npm run lint

      - name: Lint workflow files
        run: npm run lint:action

      - name: Run all tests with coverage
        run: npm test

      - name: Publish coverage to Code Climate
        uses: paambaati/codeclimate-action@v3.0.0
        if: ${{ matrix.ENABLE_CODE_COVERAGE }}
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          debug: true
          verifyDownload: true
