name: CI

on:
  push:
    branches:
      - master
      - releases/*
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  lint:
    name: 'Typecheck, code style and lint'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
        node:
          - '16'
        architecture:
          - 'x64'

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-fund

      - name: Typecheck the code
        run: npm run lint:typecheck

      - name: Lint the code (ESLint)
        run: npm run lint:eslint

      - name: Lint the code (Prettier)
        run: npm run lint:prettier

      - name: Lint workflow files
        run: npm run lint:action

  test:
    name: 'Unit tests'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
        node:
          - '14'
          - '16'
        architecture:
          - 'x64'

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-fund

      - name: Run all tests
        run: npm run test

  coverage:
    name: 'Coverage'
    needs: [lint, test]

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
        node:
          - '16'
        architecture:
          - 'x64'

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-fund

      - name: Publish code coverage (Jest) to Code Climate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
          debug: true
          verifyDownload: true
